PRODUCT_BRAND_NAME="Apla"
DB_HOST="apla-db"
DB_NAME_PREFIX="apla"
DB_USER="postgres"
DB_PASSWORD="apla"
CENT_URL="http://apla-cf:8000"

BLEX_REPO_URL="https://github.com/GenesisKernel/blockexplorer"
BLEX_BRANCH="develop"
BLEX_DB_NAME_PREFIX="apla"
BLEX_DB_HOST="apla-db"
BLEX_DB_PORT="$DB_PORT"
BLEX_DB_USER="postgres"
BLEX_DB_PASSWORD="apla"
BLEX_REDIS_URL="redis://genesis-rq:6379/0"
